# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 01:35
from __future__ import unicode_literals

import circon.warehouse.products.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units_measures', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=100)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('image', models.ImageField(blank=True, upload_to=circon.warehouse.products.models.content_file_products)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units_measures.UnitsMeasures')),
            ],
        ),
    ]
