# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20160711_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'permissions': (('to_access_warehouse', 'Puede acceder a almacen'), ('add_entry', 'Puede agregar entrada'), ('update_entry', 'Puede actualizar entrada'), ('delete_entry', 'Puede eliminar entrada'), ('add_exit', 'Puede agregar salida'), ('update_exit', 'Puede actualizar salida'), ('delete_exit', 'Puede eliminar salida'), ('to_access_inventory', 'Puede acceder inventario'), ('to_access_request', 'Puede acceder solicitudes'), ('to_access_search', 'Puede acceder busquedas'))},
        ),
    ]
