# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 15:32
from __future__ import unicode_literals

import audit_log.models.fields
import circon.warehouse.products.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('units_measures', '0001_initial'),
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_auto_20160711_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsAuditLogEntry',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('products', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=100)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('image', models.ImageField(blank=True, upload_to=circon.warehouse.products.models.content_file_products)),
                ('active', models.BooleanField(default=True)),
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('action_type', models.CharField(choices=[('I', 'Created'), ('U', 'Changed'), ('D', 'Deleted')], editable=False, max_length=1)),
                ('action_user', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_products_audit_log_entry', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units_measures.UnitsMeasures')),
            ],
            options={
                'ordering': ('-action_date',),
                'default_permissions': (),
            },
        ),
    ]
