# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountplan',
            options={'permissions': (('to_access_accounting', 'Puede acceder a contabilidad'),)},
        ),
    ]
