# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_auto_20160709_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'permissions': (('to_access_purchase', 'Puede acceder a compras'),)},
        ),
    ]
