# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_auto_20160711_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date_purchase',
            field=models.DateField(blank=True),
        ),
    ]
