# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 12:51
from __future__ import unicode_literals

import audit_log.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productsauditlogentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0007_auto_20160711_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseAuditLogEntry',
            fields=[
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_purchase', models.DateField(blank=True, null=True)),
                ('n_purchase', models.IntegerField(blank=True, db_index=True)),
                ('applicant', models.CharField(blank=True, max_length=100)),
                ('observation', models.TextField(blank=True, max_length=250)),
                ('base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, default='0', max_length=1)),
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('action_type', models.CharField(choices=[('I', 'Created'), ('U', 'Changed'), ('D', 'Deleted')], editable=False, max_length=1)),
                ('action_user', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_purchase_audit_log_entry', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
                'ordering': ('-action_date',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetailAuditLogEntry',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_product', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('action_type', models.CharField(choices=[('I', 'Created'), ('U', 'Changed'), ('D', 'Deleted')], editable=False, max_length=1)),
                ('action_user', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_purchasedetail_audit_log_entry', to=settings.AUTH_USER_MODEL)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.Purchase')),
            ],
            options={
                'default_permissions': (),
                'ordering': ('-action_date',),
            },
        ),
    ]
