# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-04 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_purchaseauditlogentry_purchasedetailauditlogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetail',
            name='quan_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchasedetailauditlogentry',
            name='quan_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
