# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0002_auto_20160711_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycompany',
            name='rif',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
