# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0003_auto_20160711_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycompany',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
